### ISSUE TITLE
Are you the first who adopts GPT-2 to Russian?

### ISSUE THREAD

**Issue by utahman** [mgrankin/ru_transformers#1]

**Comment by mgrankin** [comment]
I’m sure I’m not. @rkfg have tried to to that a long ago and composed a repo https://github.com/rkfg/gpt-2
I believe many people did that in private companies. 

But, I haven’t seen any publicly released model weights. And I haven’t seen anyone to use progressive layer unfreezing - this is the correct way to use transfer learning. And nobody have tried to train PyTorch/Transformers model on TPU. So this repo is adding some value.
