### ISSUE TITLE
run_lm_finetuning.py is different than the one of huggingface

### ISSUE THREAD

**Issue by piegu** [mgrankin/ru_transformers#10]
Hi,

Thank you very much for your work on training gpt-2 in a language other than English!

A question: I would like to know why your `run_lm_finetuning.py` file is different from the one of huggingface on [https://huggingface.co/transformers/examples.html#language-model-fine-tuning](https://huggingface.co/transformers/examples.html#language-model-fine-tuning)?

Direct link to script: [https://github.com/huggingface/transformers/blob/master/examples/run_lm_finetuning.py](https://github.com/huggingface/transformers/blob/master/examples/run_lm_finetuning.py)

Thank you.

**Comment by mgrankin** [comment]
Hello, 

I started from huggingface's example and build on it. Any particular piece of code you curious about?

**Comment by piegu** [comment]
Thanks. I focused on a particular code in this other issue: https://github.com/mgrankin/ru_transformers/issues/11
