### ISSUE TITLE
Do you plan to open trained model for public access?

### ISSUE THREAD

**Issue by andorxornot** [mgrankin/ru_transformers#2]
I am waiting for this! To experiment with songs

**Comment by mgrankin** [comment]
Yes! You can download the Small (124M) model already, the Medium (355M) will be ready in a week or so.

`aws s3 sync --no-sign-request s3://models.dobro.ai/gpt2/ru gpt2`

Also you can try in out in a web interface 

https://text.skynet.center

Or you can play with poetry (small model fine-tuned with poetry) via Telegram chat bot `@NeuroPoetBot`.

**Comment by utahman** [comment]
Only one sentence generated? Can you make it longer?

**Comment by mgrankin** [comment]
You can play with raw API on a docs page, it allows for 500 tokens at once https://models.skynet.center/docs#/default/gen_sample_gpt2_medium__post

Press "Try It out" and set your prompt in the request body

```
{
  "prompt": "Тест",
  "length": 500,
  "num_samples": 1,
  "allow_linebreak": false
} 
```

**Comment by RefalMachine** [comment]
Hello, thank you for a great work!

Is there a way to load model without aws account?

**Comment by mgrankin** [comment]
You don't need an AWS account. Just do `pip install awscli` and then following should work

`aws s3 sync --no-sign-request s3://models.dobro.ai/gpt2/ru gpt2`

**Comment by mgrankin** [comment]
The medium model is available to download.
