### ISSUE TITLE
temperature vs overfitting?

### ISSUE THREAD

**Issue by eps696** [mgrankin/ru_transformers#24]
this may be rather generic question for NLP/NLG - 
does temperature increase help fighting overfit somehow?

**Comment by mgrankin** [comment]
No. Temperature doesn't applicable during the training. It's a parameter you use to generate text.

**Comment by eps696** [comment]
sure, i mean - does increased temperature helps to provide more sensible variety from overfitted (for whatever reasons) models at generation stage? or it would just "make some noise", going pure schizo?
