### ISSUE TITLE
Когда на GPT-3 переедете?

### ISSUE THREAD

**Issue by AlexRMU** [mgrankin/ru_transformers#26]
Боюсь представить что получится...

**Comment by AlexRMU** [comment]
блин ну ок

**Comment by fantik11** [comment]
GPT-3 ещё нет в открытом доступе

**Comment by AlexRMU** [comment]
https://github.com/sberbank-ai/ru-gpts мб?

**Comment by mgrankin** [comment]
По ссылке прекрасный проект Сбера. Кодовая база похожая (transformers), но более свежая. Код чистый, модель натренирована качественно. Размер модели - large (774М параметров), что в два раза больше моей medium. На моем validation set получился perplexity 14 (против 21 на medium модели). Рекомендую использовать. Я свой проект уже перевел на их модель.

**Comment by fen0s** [comment]
> 
> 
> По ссылке прекрасный проект Сбера. Кодовая база похожая (transformers), но более свежая. Код чистый, модель натренирована качественно. Размер модели - large (774М параметров), что в два раза больше моей medium. На моем validation set получился perplexity 14 (против 21 на medium модели). Рекомендую использовать. Я свой проект уже перевел на их модель.

Только оптимизация такая, что чёрт ногу сломит, учитывая что даже с градиентной оптимизацией модель никак не хочет тренироваться на колабе, а с оптимизацией уровня O3 вовсе ломается...

**Comment by AlexRMU** [comment]
@mgrankin, а https://porfirevich.ru/ будешь переводить? Или мне закрывать issue?
