### ISSUE TITLE
Training doesn't start, just says "loading weights..."

### ISSUE THREAD

**Issue by fen0s** [mgrankin/ru_transformers#31]
```
08/08/2020 14:07:25 - INFO - transformers.modeling_utils -   loading weights file ../all/classic/m_checkpoint-3396533/pytorch_model.bin`
```
On that line, the script just stops. No error message or anything, but training doesn't start either. Running it on Colab. Using all the libraries from pip freeze posted here in issues. What's wrong?

**Comment by mgrankin** [comment]
Hello,

I've run the code only on TPU and local GPU. It would be great to have the code run on Colab, but I haven't seed anyone who did that. If you manage to run it, please, contribute to the project.

**Comment by fen0s** [comment]
Colab shouldn't be way too different, I mean you certainly can use transformers lib here. Only question here is why it stops after loading weights and doesn't initialize training after loading the model...

**Comment by fen0s** [comment]
Managed to get things running, the problem was in library verisions.
