### ISSUE TITLE
774M model?

### ISSUE THREAD

**Issue by fen0s** [mgrankin/ru_transformers#35]
It's being mentioned in README briefly when setting up configs and env variables, but doesn't seem to be present on server. Was there ever 774M model trained on russian corpus? Quoting from README:
```
# GPT-2 774M, final perplexity 21.09?

export CUDA_VISIBLE_DEVICES=3
export MODEL_SIZE=gpt2-large
export OUTPUT=output_yt/l
export BS=1
export LR=1e-5
```

**Comment by mgrankin** [comment]
Hi, I've been able to start training 774M with GPUs, but didn't completed the training. With TPUs I got OOM error and decided to give it a break.

**Comment by fen0s** [comment]
Are you planning to continue training it? Sorry for late response.

**Comment by mgrankin** [comment]
Yes, someday. Not sure when.
