### ISSUE TITLE
GOOGLE Collab sheet spawning ru_transformers folders

### ISSUE THREAD

**Issue by broAir** [mgrankin/ru_transformers#36]
Add this line to the google collab sheet 
`!rm -rf '/content/ru_transformers' || :` 
before `!git clone https://github.com/mgrankin/ru_transformers` 
otherwise it starts to spawn new folders every time the script re-runs (bsc of error or whatever)

**Comment by broAir** [comment]
@Kepler-Br

**Comment by Kepler-Br** [comment]
Done. Thank you
