### ISSUE TITLE
Run on CPU

### ISSUE THREAD

**Issue by mosvlad** [mgrankin/ru_transformers#38]
Is it possible to run this model for evaluate on CPU?

**Comment by mgrankin** [comment]
Hi, yes, you can run it on CPU.

**Comment by mosvlad** [comment]
> Hi, yes, you can run it on CPU.

But apex not builds on my system. By running :
pip uninstall apex; 
git clone https://github.com/NVIDIA/apex.git;
cd apex;
python setup.py install --cuda_ext --cpp_ext

system:
ubuntu 18.04
Intel Cascade Lake

**Comment by mgrankin** [comment]
Skip the Apex installation. Apex is the library for half-precision computation on NVIDIA GPUs. It makes things run faster on GPUs, but you don't need it.
