### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by Dmitriuso** [mgrankin/ru_transformers#41]
Hey guys,
I've got a problem with the Colab for fine-tuning, it returns a Runtime error every time I try to launch `run_lm_finetuning.py`:
``` 
RuntimeError: Found param transformer.wte.weight with type torch.FloatTensor, expected torch.cuda.FloatTensor.
When using amp.initialize, you need to provide a model with parameters
located on a CUDA device before passing it no matter what optimization level
you chose. Use model.to('cuda') to use the default device.
```
Maybe I'm doing something wrong... Could you give me a hint? 
Thank you in advance.

**Comment by mgrankin** [comment]
Hi,
You can try ping the colab author @broAir

**Comment by Dmitriuso** [comment]
@mgrankin Thank you, I'll try to 👍

**Comment by mariapotashnyk** [comment]
I've got the same error by now. @Dmitriuso did you get any help?

**Comment by Dmitriuso** [comment]
> I've got the same error by now. @Dmitriuso did you get any help?

`%set_env CUDA_VISIBLE_DEVICES=0` that should work
