### ISSUE TITLE
Website doesn't respond

### ISSUE THREAD

**Issue by Vad1mChK2** [mgrankin/ru_transformers#47]
When I try to continue my story, this
![Screenshot_20210423-101612_Chrome](https://user-images.githubusercontent.com/71339785/115833969-557a0900-a41d-11eb-9705-2c6d54bd5a36.jpg)
happens over and over again on different devices, which started yesterday in the evening.
The neural network doesn't respond on any device, and many people report about having the same issue.

**Comment by Vad1mChK2** [comment]
Ah yes, it seems the website has been repaired

**Comment by Vad1mChK2** [comment]
The network does not respond again

**Comment by Vad1mChK2** [comment]
![image](https://user-images.githubusercontent.com/71339785/120066250-723dd800-c07e-11eb-839b-59eea9d778dd.png)
The website does not respond once again. Reopen, perhaps?

**Comment by never-light** [comment]
It seems that the problem is happening again.

**Comment by mgrankin** [comment]
Yeah, that happens. Ping me on twitter next time, pls.
http://twitter.com/mgrankin
