### ISSUE TITLE
Actual requirements.txt for run rest.py

### ISSUE THREAD

**Issue by 4n70w4** [mgrankin/ru_transformers#48]
Hi!

I run `pip3 install -r .\tpu_requirements.txt` but after run `python3 .\rest.py` get more errors, for example:

```
Traceback (most recent call last):
  File "ru_transformers\rest.py", line 77, in <module>
    from pydantic import BaseModel, Schema
ImportError: cannot import name 'Schema' from 'pydantic' (C:\Users\jjj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pydantic\__init__.cp39-win_amd64.pyd)
```

Provide please actual version of `requirements.txt` for run `rest.py`

**Comment by mgrankin** [comment]
Hi, this repository is going into archive mode. Pls, consider more recent https://github.com/sberbank-ai/ru-gpts
