### ISSUE TITLE
Отказ от копирайта на генерируемые тексты

### ISSUE THREAD

**Issue by iLeonidze** [mgrankin/ru_transformers#5]
Пожалуйста, если возможно, укажите что все генерируемые тексты находятся под [СС0](https://creativecommons.org/publicdomain/zero/1.0/deed.ru). Это сделает возможным использовать их в качестве свободных датасетов, например для [Mozilla Common Voice](https://voice.mozilla.org/ru).

**Comment by mgrankin** [comment]
That is unnecessary. Only works created by a human can be protected by copyright.
