### ISSUE TITLE
Limits on a web service?

### ISSUE THREAD

**Issue by Disinterpreter** [mgrankin/ru_transformers#8]
Good day guys, I added your system to my VK bot. But I didn't see limits. I hope my small bot won't be a problem for you. Thanks!

My commit is: https://github.com/Disinterpreter/perl-vk-bot/commit/1f0fdf80c9ab264befffc6052c15a2e2f423bd29#diff-b8426a177e7f1a5b01a99d88a34d1c93

**Comment by mgrankin** [comment]
The limit is 0. You shouldn't use the web service with your bot. Please, download the model and deploy it on your server.

**Comment by Disinterpreter** [comment]
I know, but need I have the good GPU for deploy this feature or not?

**Comment by mgrankin** [comment]
GPU would be nice, although you can use CPU if you don't mind the speed.

**Comment by Disinterpreter** [comment]
> 
> 
> GPU would be nice, although you can use CPU if you don't mind the speed.

Okay! Thanks. I'll be try to install it. But anyway my bot is too little to I can make a large flood of requests.
